platform :ios, '8.0'

target 'Ha' do

pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'Reachability'
pod 'AVOSCloud' 
pod 'JVFloatLabeledTextField'
pod 'IQKeyboardManager','3.3.7'
pod 'BaiduMapKit'
pod 'AFNetworking'

end
